import type { Metadata } from "next";
import { Roboto, Lato } from "next/font/google";
import "./globals.css";
import "./globalicon.css";
import Header from "@/components/ui/header";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

const lato = Lato({
  weight: ["100", "300", "400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${lato.variable} flex min-h-screen flex-col font-main`}
      >
        <Header />
        <div className="flex-1 py-10">{children}</div>
      </body>
    </html>
  );
}
